name: Deploy
on:
  push:
    branches:
      - main
      - ci/github-action
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        run: |
          sudo apt install hugo
      - name: Build Hugo
        run: |
          hugo --minify
