name: Deploy
on:
  push:
    branches:
      - main
      - ci/github-action
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
      - name: Setup Hugo
        run: |
          sudo apt install hugo
      - name: Build Hugo
        run: |
          hugo --minify
      - name: Deploy to S3
        run: |
          echo >> config.toml
          echo "URL = ${{ secrets.S3_URL }}" >> config.toml
          echo "cloudFrontDistributionID = ${{ secrets.CF_DISTRIBUTION_ID }}" >> config.toml
          echo >> config.toml
          hugo deploy
